let value =[12,3,4,8]
value.push(5,243567)
console.log(value)
value.pop()
console.log(value)
value.shift()
console.log(value)
console.log(value.unshift(10))
console.log(value)
value.splice(1,1,68,45)
console.log(value)
